[package]
name = "language"
version = "0.1.0"
authors = ["howardwu <howardwu@berkeley.edu>"]
edition = "2018"

[dependencies]
from-pest = "0.3.1"
lazy_static = "1.3.0"
pest = "2.0"
pest_derive = "2.0"
pest-ast = "0.3.3"
